openapi: '3.0.2'
info:
  title: Quotation API
  description: Get a valid quote online
  version: '1.0'
  contact: 
    email : 'shiffana95@gmail.com'
servers:
  - url : https://api.server.test/v1
tags:
    - name: RFQ
paths:
  /rqfs:
    post:
      tags:
        - RFQ
      operationId: getQuote
      description: Request a quoute 
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        '200':
          description: OK


components :
   schemas:
     Quotation:
       type: object
       properties:
          id:
            type: integer
            format: uuid
          product:
            type: string
            maxLength: 20
            pattern: '(\w+\W*)*'
          quantity:
            type: integer
            format: int32
            minimum: 0
            maximum: 1000
          price:
            type: number
            minimum: 0
            maximum: 1000
          shipment:
            type: string
            enum:
             - FOB
             - DAT
          mode:
            type: string
            pattern: "[A-Z]{3}"
            maxLength: 3
